INSERT IGNORE INTO `autoexec_type` VALUES (1, 'INSPECT', '巡检', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (2, 'CMDB', '自动采集', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (3, 'TEST', '测试用工具', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (4, 'INSTALL', '软件安装配置', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (5, 'START_STOP', '启停操作', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (6, 'NATIVE', '调度器内置工具', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (7, 'BASIC', '基础工具', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (8, 'TEMP', '临时使用', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (9, 'BUILD', '编译打包', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (10, 'BIZ_JOBS', '作业调度', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (11, 'DEPLOY', '自动发布', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (12, 'BACKUP', '备份', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (13, 'SQL_FILE', 'SQL处理', NULL, 'system', 'factory');
INSERT IGNORE INTO `autoexec_type` VALUES (14, 'DR_SWITCH', '灾备切换', NULL, 'system', 'factory');

INSERT IGNORE INTO `autoexec_type_authority` VALUES (1, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (1, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (2, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (2, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (3, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (3, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (4, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (4, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (5, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (5, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (6, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (6, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (7, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (7, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (8, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (8, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (9, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (9, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (10, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (10, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (11, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (11, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (12, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (12, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (13, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (13, 'review', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (14, 'add', 'common', 'alluser');
INSERT IGNORE INTO `autoexec_type_authority` VALUES (14, 'review', 'common', 'alluser');